CRITICAL - 2022-05-01 00:18:12 --> Class 'App\Controllers\App\Models\UsuarioModel' not found
#0 C:\xampp\htdocs\food\system\CodeIgniter.php(809): App\Controllers\Password->__construct()
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-01 00:24:38 --> Class 'App\Filters\Throttle' not found
#0 C:\xampp\htdocs\food\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('password/proces...', 'before')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-01 03:27:14 --> Argument 1 passed to App\Controllers\Admin\Usuarios::buscaUsuarioOu404() must be of the type int or null, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 96
#0 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(96): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Admin\Usuarios->show('images', 'logo.svg')
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#3 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-01 03:27:14 --> Argument 1 passed to App\Controllers\Admin\Usuarios::buscaUsuarioOu404() must be of the type int or null, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 96
#0 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(96): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Admin\Usuarios->show('images', 'logo-mini.svg')
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#3 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-01 03:27:14 --> Argument 1 passed to App\Controllers\Admin\Usuarios::buscaUsuarioOu404() must be of the type int or null, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 96
#0 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(96): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face4.jpg')
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#3 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-01 03:27:14 --> Argument 1 passed to App\Controllers\Admin\Usuarios::buscaUsuarioOu404() must be of the type int or null, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 96
#0 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(96): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face2.jpg')
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#3 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-01 03:27:14 --> Argument 1 passed to App\Controllers\Admin\Usuarios::buscaUsuarioOu404() must be of the type int or null, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 96
#0 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(96): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face3.jpg')
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#3 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-01 03:27:14 --> Argument 1 passed to App\Controllers\Admin\Usuarios::buscaUsuarioOu404() must be of the type int or null, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 96
#0 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(96): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
#1 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face5.jpg')
#2 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#3 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2022-05-01 09:07:37 --> Error connecting to the database: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.

CRITICAL - 2022-05-01 09:07:37 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.

#0 C:\xampp\htdocs\food\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\food\app\Models\UsuarioModel.php(97): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\food\app\Controllers\Password.php(28): App\Models\UsuarioModel->buscaUsuarioPorEmail('herculano@aluno...')
#6 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Password->processaEsqueci()
#7 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Password))
#8 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-05-01 09:08:22 --> Não há dados para update.
#0 C:\xampp\htdocs\food\system\BaseModel.php(846): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\food\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#2 C:\xampp\htdocs\food\system\BaseModel.php(656): CodeIgniter\Model->update('22', Object(App\Entities\Usuario))
#3 C:\xampp\htdocs\food\app\Controllers\Password.php(39): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#4 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Password->processaEsqueci()
#5 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Password))
#6 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2022-05-01 19:23:18 --> Não há dados para update.
#0 C:\xampp\htdocs\food\system\BaseModel.php(846): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\food\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#2 C:\xampp\htdocs\food\system\BaseModel.php(656): CodeIgniter\Model->update('22', Object(App\Entities\Usuario))
#3 C:\xampp\htdocs\food\app\Controllers\Password.php(83): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#4 C:\xampp\htdocs\food\system\CodeIgniter.php(832): App\Controllers\Password->processaReset('ca93bb38a2f6515...')
#5 C:\xampp\htdocs\food\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Password))
#6 C:\xampp\htdocs\food\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\food\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
ERROR - 2022-05-01 22:46:58 --> Error connecting to the database: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente.

